name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get dove
        uses: pontem-network/get-dove@main
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dove package build

      - name: Test
        run: dove package test

  prove:
    name: Prove
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get dove
        uses: pontem-network/get-dove@add-get-boogie
        with:
          version: latest
          boogie: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: dove package prove
